### PR TITLE
added some extenders, hope you :heart: them

### PR DESCRIPTION
**Pull request by luceos**

### CODE REVIEW

**Review by dsevillamartin — COMMENTED** [review]
Nice! We might want to make some extenders accept `callable`, that way there can be some logic.

For example, for the extender that disables the flood gate, maybe the extension had settings saved in the database that it wants to retrieve and parse (and maybe filter) before passing them to the extender. See [ExtensionSettings](https://github.com/FriendsOfFlarum/extend/blob/f2314f82c3e838e0ee19ac65441b8a1a5a29c391/src/Extend/ExtensionSettings.php) for an example.

Still great tho ❤️

**Comment by luceos** [comment]
Feel free to PR against my branch with a proposal ;) But yeah possibly makes sense to do that on all extenders. Should this be a trait perhaps we apply to all our extenders? Or perhaps an abstract Extender?

**Comment by dsevillamartin** [comment]
🤔 I think only the provider one will help with b14 ⚰️ 

Not sure if we still want to merge this / include these.

**Comment by Ralkage** [comment]
@luceos most of these extenders are now in core except for the Environment and DisableFloodGate extenders ( `CheckingForFlooding` was previously depreciated (https://github.com/flarum/core/commit/8e25bcb68f86cc992c46dfa70368419fe9f936ac) and removed in b16); do you still want us to at least review adding those extenders or scrap this PR altogether?

**Comment by luceos** [comment]
I think there's no need for them anymore.

**Pull request closed without merging**
